In [111]:
import pandas as pd
import numpy as np
import pickle

from sklearn.preprocessing import OneHotEncoder, MinMaxScaler

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [108]:
df = pd.read_csv('./data/Heart Classification Task - Data.csv')
df.head()
df.shape

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

(303, 14)

In [109]:
numeric_variable = ['trestbps', 'chol', 'thalach', 'oldpeak', 'age']
categorical_variable = ['sex', 'cp', 'fbs', 'restecg', 'thalach', 'exang', 'slope', 'ca', 'thal']

# Pipeline

**numeric**

X -> Logarithm-transform -> Normalize -> X_new

In [97]:
tmp = df[numeric_variable].copy()
tmp = np.log1p(tmp)

In [98]:
mm_enc = MinMaxScaler()

In [99]:
num_feat = mm_enc.fit_transform(tmp)
num_feat

array([[0.57341028, 0.409432  , 0.71450578, 0.60479912, 0.7929635 ],
       [0.42875423, 0.45641713, 0.92594205, 0.7619127 , 0.24739503],
       [0.42875423, 0.32078956, 0.84572288, 0.44348166, 0.35213836],
       ...,
       [0.56423945, 0.28384035, 0.65521932, 0.75052874, 0.87168932],
       [0.42875423, 0.02587018, 0.46011166, 0.39940476, 0.68994007],
       [0.42875423, 0.41796657, 0.85681206, 0.        , 0.68994007]])

**categorical**

X -> One-hot-encoding -> X_new

In [100]:
oh_enc = OneHotEncoder()

In [101]:
cat_feat = oh_enc.fit_transform(df[categorical_variable]).todense()
cat_feat

matrix([[0., 1., 0., ..., 1., 0., 0.],
        [0., 1., 0., ..., 0., 1., 0.],
        [1., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 1., 1., ..., 0., 0., 1.],
        [0., 1., 1., ..., 0., 0., 1.],
        [1., 0., 0., ..., 0., 1., 0.]])

In [102]:
comb_feat = np.hstack(
    [num_feat, cat_feat]
)
comb_feat

matrix([[0.57341028, 0.409432  , 0.71450578, ..., 1.        , 0.        ,
         0.        ],
        [0.42875423, 0.45641713, 0.92594205, ..., 0.        , 1.        ,
         0.        ],
        [0.42875423, 0.32078956, 0.84572288, ..., 0.        , 1.        ,
         0.        ],
        ...,
        [0.56423945, 0.28384035, 0.65521932, ..., 0.        , 0.        ,
         1.        ],
        [0.42875423, 0.02587018, 0.46011166, ..., 0.        , 0.        ,
         1.        ],
        [0.42875423, 0.41796657, 0.85681206, ..., 0.        , 1.        ,
         0.        ]])

In [103]:
target = df['target'].values.reshape((-1, 1))
# target

In [104]:
pickle.dump(num_feat, open('./data/01_num_feat.pkl', 'wb'))
pickle.dump(cat_feat, open('./data/01_cat_feat.pkl', 'wb'))
pickle.dump(comb_feat, open('./data/01_comb_feat.pkl', 'wb'))
pickle.dump(target, open('./data/01_target.pkl', 'wb'))